# Generated by Django 3.2.6 on 2021-08-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210812_1424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Acount_Login',
        ),
    ]
