# Generated by Django 3.2.6 on 2021-08-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_login_acount_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount_login',
            name='IDwlgns',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
